# Generated by Django 5.0.6 on 2024-06-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='materias_logo'),
        ),
    ]
